services:
  nginx:
    container_name: smartnest-nginx
    image: nginx:alpine
    ports:
      - "3000:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl:ro  # Mount SSL certificates
    depends_on:
      - backend
      - webui
    restart: unless-stopped

  backend:
    container_name: smartnest-backend
    build:
      context: ./app/
      dockerfile: Dockerfile
    expose:
      - "5000"
    devices:
      - "/dev/snd:/dev/snd"  # Pass all sound devices
    env_file:
      - .env
    environment:
      - PULSE_SERVER=unix:/tmp/pulseaudio.socket
      - FLASK_ENV=development
    volumes:
      - ./app:/app
      - /tmp/pulseaudio.socket:/tmp/pulseaudio.socket
      - /etc/machine-id:/etc/machine-id:ro  # Needed for PulseAudio
      - /var/lib/dbus:/var/lib/dbus:ro
    restart: unless-stopped
    tty: true

  webui:
    container_name: smartnest-webui
    build:
      context: ./smartnest-webui/
      dockerfile: Dockerfile
    expose:
      - "3000"
    volumes:
      - ./smartnest-webui/src:/app/src
      - ./smartnest-webui/public:/app/public
    env_file:
      - .env
    environment:
      - WATCHPACK_POLLING=true
    restart: unless-stopped

networks:
  default:
    name: smartnest