services:
  backend:
    container_name: smartnest-backend
    build:
      context: ./app/
      dockerfile: Dockerfile
      target: prod
    ports:
      - "5000:5000"
    devices:
      - "/dev/snd:/dev/snd"  # Pass all sound devices
    environment:
      - PULSE_SERVER=unix:/tmp/pulseaudio.socket
      - FLASK_ENV=production
    env_file:
      - .env
    volumes:
      - /tmp/pulseaudio.socket:/tmp/pulseaudio.socket
      - /etc/machine-id:/etc/machine-id:ro  # Needed for PulseAudio
      - /var/lib/dbus:/var/lib/dbus:ro
      - ./app/smartnest/data:/app/smartnest/data
    restart: unless-stopped
  webui:
    container_name: smartnest-webui
    build:
      context: ./smartnest-webui/
      dockerfile: Dockerfile
      target: prod
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped

networks:
  default:
    name: smartnest